### ISSUE TITLE
not a recognized ConCommand or ConVar.

### ISSUE THREAD

**Issue by Acouya** [KingEnderBrine/-RoR2-MidRunArtifacts#1]
Whenever I attempt to use any of the console commands added by the mod I'm greeted with the console stating they aren't recognized.

**Comment by KingEnderBrine** [comment]
Send a log, you probably have another mod that breaks the game scanning mods for console commands

**Comment by Acouya** [comment]
I actually did a bit of testing by myself and it seems to not get along with any of the mods I have that add artifacts, those being Risky Artifacts, Artifact of Potential, and ChensClassicItems.

**Comment by KingEnderBrine** [comment]
The issue is only with `ChensClasscItems`, other works fine

**Comment by Acouya** [comment]
Well, while strange, that is correct and also a mod I'm pretty fine with ditching. Thanks a ton!
