### ISSUE TITLE
Doesn't work on dedicated servers.

### ISSUE THREAD

**Issue by Moffein** [KingEnderBrine/-RoR2-MidRunArtifacts#2]
When trying to use this command in the RoR2 Dedicated Server console, it gives the message: "You must be a lobby leader to use this command." since the check in the code only accounts for listen servers.

**Comment by KingEnderBrine** [comment]
Well, the check is there for a reason, since console commands executed on a client if you are not host it will either do nothing or throw an error. I think I will add a config option to listen for commands in the chat for such cases.

**Comment by Moffein** [comment]
The message is given if you directly enter console commands into the server console, which is the host in this situation.
Though having chat commands to do it would be pretty useful as well. (would be good to have a config option to enable/disable it)

**Comment by KingEnderBrine** [comment]
Published an update. Added config for chat commands and simplified server check which fixed your issue with DS.
